MODEL:
  pointnet_fp_modules:
  - mlp:
    - 256
    - 256
  - mlp:
    - 256
    - 128
  - mlp:
    - 128
    - 128
    - 128
  pointnet_sa_module:
    group_all: true
    mlp:
    - 256
    - 512
    - 1024
  pointnet_sa_modules:
  - mlp_list:
    - - 32
      - 32
      - 64
    - - 64
      - 64
      - 128
    - - 64
      - 96
      - 128
    npoint: 2048
    nsample_list:
    - 32
    - 64
    - 128
    radius_list:
    - 0.02
    - 0.04
    - 0.08
  - mlp_list:
    - - 64
      - 64
      - 128
    - - 128
      - 128
      - 256
    - - 128
      - 128
      - 256
    npoint: 512
    nsample_list:
    - 64
    - 64
    - 128
    radius_list:
    - 0.04
    - 0.08
    - 0.16
  - mlp_list:
    - - 64
      - 64
      - 128
    - - 128
      - 128
      - 256
    - - 128
      - 128
      - 256
    npoint: 128
    nsample_list:
    - 64
    - 64
    - 128
    radius_list:
    - 0.08
    - 0.16
    - 0.32
  offset_bins:
  - 0.0
  - 0.016
  - 0.032
  - 0.048 
  - 0.064 
  - 0.08  
  - 0.096 
  - 0.112 
  - 0.128 
  - 0.144
  - 0.16
  bin_weights:
  - 6.48795638 
  - 1.82950438 
  - 0.71419103 
  - 0.25221229 
  - 0.114388   
  - 0.08494957
  - 0.08176531 
  - 0.09851654 
  - 0.11788804 
  - 0.21862848
  gripper_width: 0.16
  ndataset_points: 20000
  raw_num_points: 40000
  